/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export type Sublocations = {
  title: string;
  slug?: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates: [number, number];
  mapThumbnail: string | Media;
  images?: {
    image: string | Media;
    id?: string;
  }[];
  id?: string;
}[];

export interface Config {
  collections: {
    locations: Location;
    media: Media;
    'blog-posts': BlogPost;
    users: User;
  };
  globals: {
    'home-page': HomePage;
    'biography-page': BiographyPage;
    'contact-page': ContactPage;
    'blog-page': BlogPage;
    'faq-page': FaqPage;
  };
}
export interface Location {
  id: string;
  title: string;
  slug?: string;
  featuredImage: string | Media;
  sublocations?: Sublocations;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt: string;
  blurDataUrl?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface BlogPost {
  id: string;
  title: string;
  slug?: string;
  description: string;
  featuredImage: string | Media;
  content: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface HomePage {
  id: string;
  firstSection: {
    featuredImage: string | Media;
  };
  secondSection: {
    featuredImage: string | Media;
  };
  thirdSection: {
    featuredImage: string | Media;
    portraitPhoto: string | Media;
  };
  fourthSection: {
    featuredImage: string | Media;
    blogPhoto: string | Media;
    galleryPhoto: string | Media;
  };
  updatedAt?: string;
  createdAt?: string;
}
export interface BiographyPage {
  id: string;
  featuredImage: string | Media;
  biographyText: string;
  conservationSection: {
    text: string;
    image: string | Media;
  };
  updatedAt?: string;
  createdAt?: string;
}
export interface ContactPage {
  id: string;
  featuredImage: string | Media;
  updatedAt?: string;
  createdAt?: string;
}
export interface BlogPage {
  id: string;
  featuredImage: string | Media;
  updatedAt?: string;
  createdAt?: string;
}
export interface FaqPage {
  id: string;
  featuredImage: string | Media;
  faqs?: {
    question: string;
    answer: string;
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
